### ISSUE TITLE
Refactor Page "Boilerplate"

### ISSUE THREAD

**Issue by jhigginbotham64** [incentivizinggood/vize#99]
I'm noticing that the Header, Footer, and Dialog components are repeated on almost every page that gets rendered. Can we move them to a place in the component hierarchy where they won't have to be re-typed so much? Maybe, say AppRoot? Or main.jsx? I don't honestly know yet, but I'm thinking AppRoot would be the place...

**Comment by julianjear** [comment]
This might be a problem for the header since it uses a different styling class for the home page compared to the other pages (home page does not have the white background for the header initially). But for message box and footer I agree this would be a good idea. As far as the best location to place this in, I am not entirely sure. We can try it in AppRoot to see if it works well there. Any ideas on the best location for this @joshuatshaffer ?

**Comment by jhigginbotham64** [comment]
Goodness. I never understood the styling difference on the home page, it always felt like a UI bug to me. We can either just remove the home-page-only styling (which I would prefer), or parameterize the Header component. Either would allow us to proceed with this refactoring.

**Comment by joshuatshaffer** [comment]
This is fixed by #132
